In [1]:
import numpy as np

In [2]:
angulos_cero_noventa = np.array((0,30,45,60,90))
angulos_cero_noventa

array([ 0, 30, 45, 60, 90])

In [4]:
angulos_radianes = angulos_cero_noventa * np.pi/180
angulos_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [5]:
np.sin(angulos_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [6]:
np.cos(angulos_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [7]:
np.tan(angulos_radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [12]:
arreglo_random_diez = np.random.randint(-10, # Menor
                                        1000,# Mayor
                                        10)# Tamanio
#arreglo_random_diez = arreglo_random_diez * 10
arreglo_random_diez

array([316, 341,  -5, 749, 629, 425, 105, 634, 958, 449])

In [13]:
np.random.randint(10)

3

In [14]:
np.random.randint(10)

8

In [15]:
# Media
arreglo_random_diez.mean()

460.1

In [16]:
# Mediana
np.median(arreglo_random_diez)

437.0

In [18]:
# Desviacion Estandar
np.std(arreglo_random_diez)

277.2823290438826

In [19]:
# Varianza
np.var(arreglo_random_diez)

76885.48999999999