# Indices

In [1]:
import numpy as np

In [2]:
numeros = np.arange(11)**2

In [3]:
numeros

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [4]:
indices = [2,5,7]

In [5]:
numeros[indices]

array([ 4, 25, 49], dtype=int32)

In [6]:
arreglo_frutas = np.array([
    ['Piña','Manzana','Pera','Melon'],
    ['Pera','Uva','Naranja','Papaya'],
    ['Frutilla','Platano','Granadilla','Sandia']
])

In [7]:
arreglo_frutas.shape

(3, 4)

In [8]:
arreglo_filas = np.array([
    [0,0,0,0],
    [1,1,1,1],
    [2,2,2,2]
])
arreglo_filas

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

In [9]:
arreglo_columnas = np.array([
    [0,1,2,3],
    [0,1,2,3],
    [0,1,2,3]
])
arreglo_columnas

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [10]:
arreglo_frutas[arreglo_filas,arreglo_columnas]

array([['Piña', 'Manzana', 'Pera', 'Melon'],
       ['Pera', 'Uva', 'Naranja', 'Papaya'],
       ['Frutilla', 'Platano', 'Granadilla', 'Sandia']], dtype='<U10')

In [11]:
arreglo_frutas

array([['Piña', 'Manzana', 'Pera', 'Melon'],
       ['Pera', 'Uva', 'Naranja', 'Papaya'],
       ['Frutilla', 'Platano', 'Granadilla', 'Sandia']], dtype='<U10')

In [12]:
arreglo_filas2 = np.array([
    [0,0],
    [1,1],
    [2,2]
])
arreglo_filas2

array([[0, 0],
       [1, 1],
       [2, 2]])

In [13]:
arreglo_columnas2 = np.array([
    [2,3],
    [2,3],
    [2,3]
])
arreglo_columnas2

array([[2, 3],
       [2, 3],
       [2, 3]])

In [14]:
arreglo_frutas[arreglo_filas2,arreglo_columnas2]

array([['Pera', 'Melon'],
       ['Naranja', 'Papaya'],
       ['Granadilla', 'Sandia']], dtype='<U10')

In [10]:
arreglo_frutas_1D = np.array(['Piña','Manzana','Pera','Melon','Carambola','Tomate','Chirimoya','Guaba','Capulí',
                            'Uva','Naranja','Papaya','Durazno','Aguacate','Granada','Limón','Frutilla','Platano',
                            'Granadilla','Sandia','Mandarina','Achotillos','Maqueño','Lima'])
arreglo_frutas_1D.shape

(24,)

In [11]:
arreglo_frutas_3D = arreglo_frutas_1D.reshape(3,4,2)
arreglo_frutas_3D

array([[['Piña', 'Manzana'],
        ['Pera', 'Melon'],
        ['Carambola', 'Tomate'],
        ['Chirimoya', 'Guaba']],

       [['Capulí', 'Uva'],
        ['Naranja', 'Papaya'],
        ['Durazno', 'Aguacate'],
        ['Granada', 'Limón']],

       [['Frutilla', 'Platano'],
        ['Granadilla', 'Sandia'],
        ['Mandarina', 'Achotillos'],
        ['Maqueño', 'Lima']]], dtype='<U10')

In [46]:
primera_dimension = np.array([
    [[0]],
    [[1]],
    [[2]]
])
primera_dimension.shape

(3, 1, 1)

In [13]:
primera_dimension

array([[[0, 0]],

       [[1, 1]],

       [[2, 2]]])

In [45]:
segunda_dimension = np.array([
    [[0],
    [1],
    [2],
    [3]]
])
segunda_dimension.shape

(1, 4, 1)

In [41]:
segunda_dimension

array([[0],
       [1],
       [2],
       [3]])

In [48]:
tercera_dimension = np.array([
    [[0,1]]
])
tercera_dimension.shape #Funciona incluso si el arreglo es de 2D

(1, 1, 2)

In [49]:
tercera_dimension

array([[[0, 1]]])

In [50]:
arreglo_frutas_3D[primera_dimension, segunda_dimension, tercera_dimension]

array([[['Piña', 'Manzana'],
        ['Pera', 'Melon'],
        ['Carambola', 'Tomate'],
        ['Chirimoya', 'Guaba']],

       [['Capulí', 'Uva'],
        ['Naranja', 'Papaya'],
        ['Durazno', 'Aguacate'],
        ['Granada', 'Limón']],

       [['Frutilla', 'Platano'],
        ['Granadilla', 'Sandia'],
        ['Mandarina', 'Achotillos'],
        ['Maqueño', 'Lima']]], dtype='<U10')

In [19]:
arreglo_frutas_3D

array([[['Piña', 'Manzana'],
        ['Pera', 'Melon'],
        ['Carambola', 'Tomate'],
        ['Chirimoya', 'Guaba']],

       [['Capulí', 'Uva'],
        ['Naranja', 'Papaya'],
        ['Durazno', 'Aguacate'],
        ['Granada', 'Limón']],

       [['Frutilla', 'Platano'],
        ['Granadilla', 'Sandia'],
        ['Mandarina', 'Achotillos'],
        ['Maqueño', 'Lima']]], dtype='<U10')

In [20]:
arreglo_frutas_1D

array(['Piña', 'Manzana', 'Pera', 'Melon', 'Carambola', 'Tomate',
       'Chirimoya', 'Guaba', 'Capulí', 'Uva', 'Naranja', 'Papaya',
       'Durazno', 'Aguacate', 'Granada', 'Limón', 'Frutilla', 'Platano',
       'Granadilla', 'Sandia', 'Mandarina', 'Achotillos', 'Maqueño',
       'Lima'], dtype='<U10')

In [21]:
print(np.where(arreglo_frutas_3D.astype('<U1') == 'P'))

(array([0, 0, 1, 2]), array([0, 1, 1, 0]), array([0, 0, 1, 1]))


In [32]:
#Arreglo 1 Dimensión
print(arreglo_frutas_1D[np.where(arreglo_frutas_1D.astype('<U1') == 'P')])

['Piña' 'Pera' 'Papaya' 'Platano']


In [33]:
#Arreglo 3 Dimensiones
print(arreglo_frutas_3D[np.where(arreglo_frutas_3D.astype('<U1') == 'P')])

['Piña' 'Pera' 'Papaya' 'Platano']


In [5]:
url_inicial = 'https://www.fybeca.com/FybecaWeb/pages/search-results.jsf?cat=238&s=0&pp=25'

In [4]:
len('https://www.fybeca.com/FybecaWeb/pages/search-results.jsf?cat=238&s=')

68

In [9]:
url_inicial[69:]

'&pp=25'

In [16]:
grupo_urls = []
url_inicial = 'https://www.fybeca.com/FybecaWeb/pages/search-results.jsf?cat=238&s=0&pp=25'
n=0
final_de_url = url_inicial[69:]

for url in range(7):
    url_inicial = url_inicial[0:68]+str(n)+final_de_url
    grupo_urls.append(url_inicial)
    n=n+25
grupo_urls

['https://www.fybeca.com/FybecaWeb/pages/search-results.jsf?cat=238&s=0&pp=25',
 'https://www.fybeca.com/FybecaWeb/pages/search-results.jsf?cat=238&s=25&pp=25',
 'https://www.fybeca.com/FybecaWeb/pages/search-results.jsf?cat=238&s=50&pp=25',
 'https://www.fybeca.com/FybecaWeb/pages/search-results.jsf?cat=238&s=75&pp=25',
 'https://www.fybeca.com/FybecaWeb/pages/search-results.jsf?cat=238&s=100&pp=25',
 'https://www.fybeca.com/FybecaWeb/pages/search-results.jsf?cat=238&s=125&pp=25',
 'https://www.fybeca.com/FybecaWeb/pages/search-results.jsf?cat=238&s=150&pp=25']

In [48]:
precios = ["text:'$' + (15.00).formatMoney(2, ';', ',')", "text:'$' + (5.40).formatMoney(2, ';', ',')"]

In [49]:
precios

["text:'$' + (15.00).formatMoney(2, ';', ',')",
 "text:'$' + (5.40).formatMoney(2, ';', ',')"]

In [50]:
i = 0
for precio in precios:
    if(len(precio)==43):
        precios[i] = precio[12:17]
        print('43')
    else:
        precios[i] = precio[12:16]
        print('42')
    i = i+1


43
42


In [51]:
precios

['15.00', '5.40']