# Indices

In [1]:
import numpy as np

In [2]:
numeros = np.arange(11)**2

In [3]:
numeros

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [4]:
indices = [2,5,7]

In [5]:
numeros[indices]

array([ 4, 25, 49], dtype=int32)

In [6]:
arreglo_frutas = np.array([
    ['Piña','Manzana','Pera','Melon'],
    ['Pera','Uva','Naranja','Papaya'],
    ['Frutilla','Platano','Granadilla','Sandia']
])

In [7]:
arreglo_frutas.shape

(3, 4)

In [8]:
arreglo_filas = np.array([
    [0,0,0,0],
    [1,1,1,1],
    [2,2,2,2]
])
arreglo_filas

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

In [9]:
arreglo_columnas = np.array([
    [0,1,2,3],
    [0,1,2,3],
    [0,1,2,3]
])
arreglo_columnas

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [10]:
arreglo_frutas[arreglo_filas,arreglo_columnas]

array([['Piña', 'Manzana', 'Pera', 'Melon'],
       ['Pera', 'Uva', 'Naranja', 'Papaya'],
       ['Frutilla', 'Platano', 'Granadilla', 'Sandia']], dtype='<U10')

In [11]:
arreglo_frutas

array([['Piña', 'Manzana', 'Pera', 'Melon'],
       ['Pera', 'Uva', 'Naranja', 'Papaya'],
       ['Frutilla', 'Platano', 'Granadilla', 'Sandia']], dtype='<U10')

In [12]:
arreglo_filas2 = np.array([
    [0,0],
    [1,1],
    [2,2]
])
arreglo_filas2

array([[0, 0],
       [1, 1],
       [2, 2]])

In [13]:
arreglo_columnas2 = np.array([
    [2,3],
    [2,3],
    [2,3]
])
arreglo_columnas2

array([[2, 3],
       [2, 3],
       [2, 3]])

In [14]:
arreglo_frutas[arreglo_filas2,arreglo_columnas2]

array([['Pera', 'Melon'],
       ['Naranja', 'Papaya'],
       ['Granadilla', 'Sandia']], dtype='<U10')

In [15]:
arreglo_frutas_1D = np.array(['Piña','Manzana','Pera','Melon','Carambola','Tomate','Chirimoya','Guaba','Capulí',
                            'Uva','Naranja','Papaya','Durazno','Aguacate','Granada','Limón','Frutilla','Platano',
                            'Granadilla','Sandia','Mandarina','Achotillos','Maqueño','Lima'])
arreglo_frutas_1D.shape

(24,)

In [16]:
arreglo_frutas_3D = arreglo_frutas_1D.reshape(3,4,2)
arreglo_frutas_3D

array([[['Piña', 'Manzana'],
        ['Pera', 'Melon'],
        ['Carambola', 'Tomate'],
        ['Chirimoya', 'Guaba']],

       [['Capulí', 'Uva'],
        ['Naranja', 'Papaya'],
        ['Durazno', 'Aguacate'],
        ['Granada', 'Limón']],

       [['Frutilla', 'Platano'],
        ['Granadilla', 'Sandia'],
        ['Mandarina', 'Achotillos'],
        ['Maqueño', 'Lima']]], dtype='<U10')

In [17]:
primera_dimension = np.array([
    [[0,0]],
    [[1,1]],
    [[2,2]]
])
primera_dimension.shape

(3, 1, 2)

In [18]:
primera_dimension

array([[[0, 0]],

       [[1, 1]],

       [[2, 2]]])

In [19]:
segunda_dimension = np.array([
    [[0,0],
    [1,1],
    [2,2],
    [3,3]]
])
segunda_dimension.shape

(1, 4, 2)

In [20]:
segunda_dimension

array([[[0, 0],
        [1, 1],
        [2, 2],
        [3, 3]]])

In [21]:
tercera_dimension = np.array([
    [0,1]
])
tercera_dimension.shape

(1, 2)

In [22]:
tercera_dimension

array([[0, 1]])

In [23]:
arreglo_frutas_3D[primera_dimension, segunda_dimension, tercera_dimension]

array([[['Piña', 'Manzana'],
        ['Pera', 'Melon'],
        ['Carambola', 'Tomate'],
        ['Chirimoya', 'Guaba']],

       [['Capulí', 'Uva'],
        ['Naranja', 'Papaya'],
        ['Durazno', 'Aguacate'],
        ['Granada', 'Limón']],

       [['Frutilla', 'Platano'],
        ['Granadilla', 'Sandia'],
        ['Mandarina', 'Achotillos'],
        ['Maqueño', 'Lima']]], dtype='<U10')

In [24]:
arreglo_frutas_3D

array([[['Piña', 'Manzana'],
        ['Pera', 'Melon'],
        ['Carambola', 'Tomate'],
        ['Chirimoya', 'Guaba']],

       [['Capulí', 'Uva'],
        ['Naranja', 'Papaya'],
        ['Durazno', 'Aguacate'],
        ['Granada', 'Limón']],

       [['Frutilla', 'Platano'],
        ['Granadilla', 'Sandia'],
        ['Mandarina', 'Achotillos'],
        ['Maqueño', 'Lima']]], dtype='<U10')

In [25]:
arreglo_frutas_1D

array(['Piña', 'Manzana', 'Pera', 'Melon', 'Carambola', 'Tomate',
       'Chirimoya', 'Guaba', 'Capulí', 'Uva', 'Naranja', 'Papaya',
       'Durazno', 'Aguacate', 'Granada', 'Limón', 'Frutilla', 'Platano',
       'Granadilla', 'Sandia', 'Mandarina', 'Achotillos', 'Maqueño',
       'Lima'], dtype='<U10')

In [53]:
print(np.where(arreglo_frutas_3D.astype('<U1') == 'P'))

(array([0, 0, 1, 2], dtype=int64), array([0, 1, 1, 0], dtype=int64), array([0, 0, 1, 1], dtype=int64))


In [56]:
#Arreglo 1 Dimensión
print(arreglo_frutas_1D[np.where(arreglo_frutas_1D.astype('<U1') == 'P')])

['Piña' 'Pera' 'Papaya' 'Platano']


In [57]:
#Arreglo 3 Dimensiones
print(arreglo_frutas_3D[np.where(arreglo_frutas_3D.astype('<U1') == 'P')])

['Piña' 'Pera' 'Papaya' 'Platano']
