In [21]:
import numpy as np

# Ejercicios con funciones de Numpy

## Obtener los datos del archivo datos_base y generar un arreglo con los mismos, luego generar un arreglo randómico con igual cantidad de datos y de idénticas dimensiones. Finalmente, guarde los datos del arreglo generado en un archivo nuevo de nombre datos_generados

In [34]:
#Generar arreglo con los datos
path = './data/datos_base.csv'
arreglo_base = np.genfromtxt(path,delimiter=',')

In [35]:
#identificar la cantidad de datos que tiene el arreglo
arreglo_base.size

15

In [36]:
#identificar la cantidad de dimensiones del arreglo base
arreglo_base.shape

(3, 5)

In [38]:
arreglo_randomico = np.random.randint(0,1000,arreglo_base.size).reshape(arreglo_base.shape)

In [39]:
arreglo_base

array([[ 2.,  4.,  6.,  8., 10.],
       [12., 14., 16., 18., 20.],
       [22., 24., 26., 28., 30.]])

In [40]:
arreglo_randomico

array([[399, 592, 391, 155, 635],
       [493, 426, 195, 370, 487],
       [353, 271, 396, 175,  81]])

In [41]:
path_out = './data/datos_generados.csv'
np.savetxt(path_out,arreglo_randomico,delimiter=',',fmt='%4d')

## Generar un arreglo con 16 números enteros y dividirlo 2 dimensiones. Luego, crear un nuevo arreglo cuyos datos sean los mismos que el anterior sumando un número randómico generado. Finalmente, aplicar las 5 operaciones principales, el producto punto entre ambos arreglos y una matriz identidad con la misma cantidad de elementos.

In [98]:
arreglo_uno = np.arange(16)
arreglo_uno

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [99]:
arreglo_uno = arreglo_uno.reshape(4,4)
arreglo_uno

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [100]:
numero_randomico = np.random.randint(10)
numero_randomico

9

In [101]:
arreglo_dos = arreglo_uno+numero_randomico
arreglo_dos

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [102]:
#Suma de dos arreglos
arreglo_uno + arreglo_dos

array([[ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31],
       [33, 35, 37, 39]])

In [103]:
#Resta de dos arreglos
arreglo_uno - arreglo_dos

array([[-9, -9, -9, -9],
       [-9, -9, -9, -9],
       [-9, -9, -9, -9],
       [-9, -9, -9, -9]])

In [104]:
#Multiplicación de dos arreglos
arreglo_uno * arreglo_dos

array([[  0,  10,  22,  36],
       [ 52,  70,  90, 112],
       [136, 162, 190, 220],
       [252, 286, 322, 360]])

In [105]:
#División de dos arreglos
arreglo_uno / arreglo_dos

array([[0.        , 0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       , 0.4375    ],
       [0.47058824, 0.5       , 0.52631579, 0.55      ],
       [0.57142857, 0.59090909, 0.60869565, 0.625     ]])

In [106]:
#Modulo entre dos arreglos
arreglo_uno % arreglo_dos

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]], dtype=int32)

In [107]:
#Producto punto entre dos arreglos
arreglo_uno.dot(arreglo_dos)

array([[110, 116, 122, 128],
       [350, 372, 394, 416],
       [590, 628, 666, 704],
       [830, 884, 938, 992]])

In [180]:
#Matriz identidad
np.eye(arreglo_uno.shape[0])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Usando los arreglos del ejercicio anterior, realizar el producto entre la suma total de cada arreglo, la división entre los valores máximos y el módulo entre los valores mínimos

In [108]:
#Producto de la sumatoria total
arreglo_uno.sum()*arreglo_dos.sum()

31680

In [112]:
#División entre los valores máximos
arreglo_uno.max()/arreglo_dos.max()

0.625

In [113]:
#Modulo entre los valores mínimos
arreglo_uno.min()%arreglo_dos.min()

0

## Usando los mismos arreglos, realice la suma entre los 10 primeros numeros del primer arreglo y los últimos 10 del segundo en un nuevo arreglo. Luego, obtenga la media, mediana, varianza y desviación estándar de los 6 elementos centrales del nuevo arreglo.

In [128]:
arreglo_tres = arreglo_uno.flatten()[:10] + arreglo_dos.flatten()[-10:]
arreglo_tres

array([15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

In [129]:
#media de los 6 elementos centrales
arreglo_tres[2:8].mean()

24.0

In [130]:
#Mediana de los 6 elementos centrales
np.median(arreglo_tres[2:8])

24.0

In [131]:
#Desviación Estándar de los 6 elementos centrales
np.std(arreglo_tres[2:8])

3.415650255319866

In [132]:
#Varianza de los 6 elementos centrales
np.var(arreglo_tres[2:8])

11.666666666666666

## Genere un arreglo con 20 elementos randómicos entre 90 y 180. Realice la comprobación de cuales valores seno de cada elemento son menores a 1, cuales coseno son mayores a 0 y cuales tangentes son iguales a 1. Finalmente, seleccione 5 elementos en saltos de 4.

In [151]:
arreglo_cuatro = np.random.randint(90,180,20)
arreglo_cuatro

array([136, 107, 112, 136, 101, 160, 111, 104, 122, 128, 144, 176, 106,
       103,  92, 135, 140, 175, 172, 101])

In [152]:
arreglo_cuatro_radianes = arreglo_cuatro * np.pi/180
arreglo_cuatro_radianes

array([2.37364778, 1.8675023 , 1.95476876, 2.37364778, 1.76278254,
       2.7925268 , 1.93731547, 1.81514242, 2.12930169, 2.23402144,
       2.51327412, 3.07177948, 1.85004901, 1.79768913, 1.60570291,
       2.35619449, 2.44346095, 3.05432619, 3.00196631, 1.76278254])

In [153]:
#Senos menores a 1
np.sin(arreglo_cuatro_radianes)<1

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [157]:
#Cosenos mayores a 0
np.cos(arreglo_cuatro_radianes)>0

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [158]:
np.tan(arreglo_cuatro_radianes)==1

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [160]:
arreglo_cuatro[::4]

array([136, 101, 122, 106, 140])

## Usar el arreglo randómico del ejercicio anterios, dividirlo en 2 dimensiones. Obtenga la transpuesta de este arreglo, una matriz de ceros y  de unos con la misma cantidad de elementos del arreglo dividido. Finalmente, realice una vista del arreglo, dividala en arreglos irregulares.

In [169]:
arreglo_cinco = arreglo_cuatro.reshape(2,10)
arreglo_cinco

array([[136, 107, 112, 136, 101, 160, 111, 104, 122, 128],
       [144, 176, 106, 103,  92, 135, 140, 175, 172, 101]])

In [171]:
#Obtener Transpuesta
arreglo_cinco.T

array([[136, 144],
       [107, 176],
       [112, 106],
       [136, 103],
       [101,  92],
       [160, 135],
       [111, 140],
       [104, 175],
       [122, 172],
       [128, 101]])

In [181]:
#Arreglo de ceros con las mismas dimensiones
np.ones(arreglo_cinco.shape)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [182]:
#Arreglo de ceros con las mismas dimensiones
np.zeros(arreglo_cinco.shape)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [185]:
#creción vista
vista_arreglo_cinco = arreglo_cinco.view()
vista_arreglo_cinco

array([[136, 107, 112, 136, 101, 160, 111, 104, 122, 128],
       [144, 176, 106, 103,  92, 135, 140, 175, 172, 101]])

In [192]:
#Arreglo dividido en listas irregulares
np.split(vista_arreglo_cinco.flatten(), [1,3,5,10])

[array([136]),
 array([107, 112]),
 array([136, 101]),
 array([160, 111, 104, 122, 128]),
 array([144, 176, 106, 103,  92, 135, 140, 175, 172, 101])]